-- AlterTable
ALTER TABLE `booking` MODIFY `status` ENUM('PENDING', 'CONFIRMED', 'COMPLETED', 'CANCELLED') NOT NULL DEFAULT 'PENDING';

-- AlterTable
ALTER TABLE `schedule` MODIFY `status` ENUM('AVAILABLE', 'BOOKED', 'COMPLETED', 'CANCELLED') NOT NULL DEFAULT 'AVAILABLE';
